language: 'node_js'
node_js: '8'

before_script:
  - npm run extract
  - yarn install
  - yarn build
  - cp ./build/index.html ./build/404.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: ./build
  repo: christopherkade/dev-spotlight
  fqdn: devspotlight.club
  target_branch: gh-pages
  on:
    branch: master
